name: 'Terraform Plan'
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Debug - List files
        run: |
          echo "Listing project files:"
          find . -type f -print

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.3

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
        
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Install TFLint
        run: |
          curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip && unzip tflint.zip && sudo mv tflint /usr/bin/
      
      - name: Run TFLint
        run: tflint

      - name: Install TFSec
        run: |
         wget -q https://github.com/tfsec/tfsec/releases/latest/download/tfsec-linux-amd64 -O tfsec
         chmod +x tfsec
         sudo mv tfsec /usr/local/bin/

      - name: Run TFSec
        run: tfsec .

      - name: Terraform Plan
        id: plan
        run: |
          set -e
          terraform plan -no-color > plan_output.txt
        continue-on-error: true

      - name: Comment PR
        uses: actions/github-script@v5
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('plan_output.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Output of terraform plan:\n\n\`\`\`\n${output}\n\`\`\``
            });
  
      - name: Set output
        id: vars
        run: echo "output_var_name=value" >> $GITHUB_ENV