name: 'Terraform Plan'
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Debug - List files
        run: |
          echo "Listing project files:"
          find . -type f -print

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.3

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
          set -e
          output=$(terraform plan -no-color)
          echo "::set-output name=plan_output::$output"
        continue-on-error: true

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
         tflint_version: v0.45.0

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
        # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
        GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact

      - name: Install TFSec
        run: |
         wget -q https://github.com/tfsec/tfsec/releases/latest/download/tfsec-linux-amd64 -O tfsec
         chmod +x tfsec
         sudo mv tfsec /usr/local/bin/

      - name: Run TFSec
        run: tfsec .

      - name: Comment PR
        uses: actions/github-script@v5
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `Output of terraform plan:\n\n\`\`\`\n${{ steps.plan.outputs.plan_output }}\n\`\`\``;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context
              repo: context.repo.repo,
              body: output
             });
        
      - name: Set output
        id: vars
        run: echo "output_var_name=value" >> $GITHUB_ENV