name: 'Terragrunt Plan'
on:
  pull_request:
    branches: [ master ]

jobs:
  terragrunt_workdirs:
    name: 'Terragrunt WorkDir'
    runs-on: terragrunt
    container:
      image: alpine:latest    
    steps:
      - name: Installing prereq packages 
        run: apk add --no-cache curl jq
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"